framework:
    rate_limiter:
        crm_api:
            policy: 'fixed_window'
            limit: 10
            interval: '1 second'
        vtiger_api:
            policy: 'fixed_window'
            limit: 20
            interval: '1 minute'
