services:
    handler_stack_simla.guzzle:
        class: 'GuzzleHttp\HandlerStack'
        factory: ['@App\Guzzle\HandlerStackBuilder\HandlerStackBuilder', 'build']
        arguments:
            - !tagged_iterator 'guzzle.middleware.simla'

    handler_stack_vtiger.guzzle:
        class: 'GuzzleHttp\HandlerStack'
        factory: [ '@App\Guzzle\HandlerStackBuilder\HandlerStackBuilder', 'build' ]
        arguments:
            - !tagged_iterator 'guzzle.middleware.vtiger'

    http_client_simla.guzzle:
        class: 'GuzzleHttp\Client'
        arguments:
            - handler: '@handler_stack_simla.guzzle'

    http_client_vtiger.guzzle:
        class: 'GuzzleHttp\Client'
        arguments:
            $config:
                base_uri: '%vtiger.api_url%'
                handler: '@handler_stack_vtiger.guzzle'